### ISSUE TITLE
issue with genes.to.kronaTable.py to get COG.tab file 

### ISSUE THREAD

**Issue by smeeta** [EnvGen/metagenomics-workshop#18]
Hi,

I tried to run the COG from the script : 

genes.to.kronaTable.py -i PROKKA.$SAMPLE.cog -m ~/mg-workshop/reference_db/cog/cog.to.cat -H ~/mg-workshop/reference_db/cog/cat.hierarchy -n $SAMPLE -c $SAMPLE.coverage -o $SAMPLE.krona.COG.tab

I get the following error  : 

$ python genes.to.kronaTable.py \
> --infile ~/GROUP/sm/PROKKA.sm.cog \
> --mapfile ~/GROUP/sm/metagenomics-workshop-master/reference_db/cog/cog.to.cat   \
> --hierarchy ~/GROUP/sm/metagenomics-workshop-master/reference_db/cog/cat.hierarchy   \
> --outfile ~/GROUP/sm/sm.krona.COG.tab
Traceback (most recent call last):
  File "genes.to.kronaTable.py", line 200, in <module>
    if __name__ == "__main__": main()
  File "genes.to.kronaTable.py", line 157, in main
    annotations = ReadMap(args.infile) ## Read annotations the same way as above, then get length of the list for counts
  File "genes.to.kronaTable.py", line 30, in ReadMap
    ann = row[1] 
IndexError: list index out of range

Any help could be really appreciated.

regards
Smeeta

**Comment by lexikazen** [comment]
I had this issue as well. Was it ever solved?
